TodoApp/urls.py
from django.contrib import admin
from django.urls import path, include
from tracker import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tracker/', include('tracker.urls', namespace='tracker')),
    path('', views.TaskListView.as_view()),
]

tracker/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views


app_name = 'tracker'
urlpatterns = [
	path('login/', views.Login.as_view(), name='login'),
	path('logout/', LogoutView.as_view(next_page='tracker:login'), name='logout'),
	path('register/', views.Register.as_view(), name='register'),
	path('', views.TaskListView.as_view(), name='home'),
	path('<int:pk>/', views.DetailTaskView.as_view(), name='detail'),
	path('tracker/create_task/', views.CreateTaskView.as_view(), name="create"),
	path('tracker/<int:pk>/delete/', views.DeleteTaskView.as_view(), name='delete'),
	path('tracker/<int:pk>/update/', views.UpdateTaskView.as_view(), name='update'),
]

tracker/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Task(models.Model):
	name = models.CharField(max_length=250)
	description = models.TextField()
	created_date = models.DateField(auto_now_add=True)
	due_date = models.DateField()
	schedule_date = models.DateField()
	closed = models.BooleanField(default=False)
	user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)


	def __str__(self):
		return self.name

	class Meta:
		ordering = ['created_date']
		

tracker/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login
from .models import Task

class Login(LoginView):
	template_name = 'tracker/login.html'
	fields = "__all__"
	redirect_authenticated_user = True

	def get_success_url(self):
		return reverse_lazy('tracker:home')

class Register(FormView):
	template_name = 'tracker/register.html'
	form_class = UserCreationForm
	redirect_authenticated_user = True
	success_url = reverse_lazy('tracker:home')

	def form_valid(self, form):
		user = form.save()
		if user is not None:
			login(self.request, user)
		return super().form_valid(form)

	def get(self, *args, **kwargs):
		if self.request.user.is_authenticated:
			return redirect('tracker:home')
		return super().get(*args, **kwargs)



class TaskListView(LoginRequiredMixin, ListView):
	model = Task
	context_object_name = 'objects'
	template_name = 'tracker/home.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['objects'] = context['objects'].filter(user=self.request.user)
		context['count'] = context['objects'].filter(closed=False).count()

		search_input = self.request.GET.get('search-area') or ''
		if search_input:
			context['objects'] = context['objects'].filter(name__icontains=search_input)
		return context



class DetailTaskView(LoginRequiredMixin ,DeleteView):
	model = Task
	context_object_name = 'obj'
	template_name = 'tracker/detail.html'


class CreateTaskView(LoginRequiredMixin, CreateView):
	model = Task
	fields = ['name', 'description', 'due_date', 'schedule_date', 'closed']
	success_url = reverse_lazy('tracker:home')

	def form_valid(self, form):
		form.instance.user = self.request.user
		return super().form_valid(form)



class DeleteTaskView(LoginRequiredMixin ,DeleteView):
	model = Task
	success_url = reverse_lazy('tracker:home')


class UpdateTaskView(LoginRequiredMixin ,UpdateView):
	model = Task
	fields = "__all__"
	template_name_suffix = "_update_form"
	success_url = reverse_lazy('tracker:home')

tracker/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>TodoApp</title>
  </head>
  <body>
    <div class="container text-center">
      {% block content %}
      {% endblock %}
    </div>
    

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

tracker/templates/tracker/detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col d-flex justify-content-center">
			<div class="col-md-6 text-center mt-5 border border-success py-3 rounded">
				<h4 class="text-decoration-underline">Task detail: </h4>
				<p>{{obj.description}}</p>
				<small><a href="{% url 'tracker:home' %}" class="text-start">Go back</a></small>
				<small><a href="{% url 'tracker:update' obj.id %}" class="btn btn-primary">Edit</a></small>
				<small><a href="{% url 'tracker:delete' obj.id %}" class="btn btn-danger">Delete</a></small>
			</div>
		</div>
	</div>	
</div>

{% endblock %}

tracker/templates/tracker/home.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
	<div class="wrapper mt-4">
		<div class="header-bar">
			<div>
				<h1>Hi {{ request.user }}</h1>
				
				<h3 class="fst-italic">You have {{ count }} Incomplete task{{ count|pluralize:"s" }}</h3>

			</div>
		</div>
		{% if request.user.is_authenticated %}
			<div class="d-flex justify-content-around">
				<p class="text-end"><a href="{% url 'tracker:logout' %}" class="">Logout</a></p>
			</div>
		{% else %}
			<a href="{% url 'tracker:login' %}" class="">Login</a>
		{% endif %}
		<hr>
		<h1 class="text-center text-decoration-underline">My To Do List</h1>
		<form method="GET" class="mt-3">
			<input type="text" placeholder="Search taks" name="search-area" value="{{ search_input }}">
			<input type="submit" value="Search">
		</form>

		<h6 class="text-center mt-3"><a href="{% url 'tracker:create' %}">Create Task</a></h6>
		<div class="row">
			{% for obj in objects %}
				<div class="col-12 d-flex justify-content-center gy-2">
					<div class="col-md-8 col-lg-8 border border-info rounded text-center py-4 mt-3">
						{% if obj.closed %}
							<h4><i><s>Title: {{obj.name}}</s><i></h4>
							<p>Date: {{ obj.due_date }}</p>
							<p class="text-success text-center">complete</p>
						{% else %}
							<h4>Title: {{obj.name}}</h4>
							<p>Date: {{ obj.due_date }}</p>
							<small><a href="{% url 'tracker:detail' obj.id %}" class="btn btn-primary">view</a></small>
							<small><a href="{% url 'tracker:update' obj.id %}" class="btn btn-secondary">Edit</a></small>
							<small><a href="{% url 'tracker:delete' obj.id %}" class="btn btn-danger">Delete</a></small>
						{% endif %}
					</div>
				</div>
			{% endfor %}
		</div>
	</div>
</div>

{% endblock %}

tracker/templates/tracker/login.html
{% extends 'base.html' %}


{% block content %}
<h2>LOGIN</h2>
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Login">
</form>

<p>Don't have an account? <a href="{% url 'tracker:register' %}">Register</a></p>

{% endblock %}

tracker/templates/tracker/register.html
{% extends 'base.html' %}


{% block content %}

<h3>Register</h3>

<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Register">
</form>

<p>Already have an account? <a href="{% url 'tracker:login' %}">Login</a></p>
{% endblock %}

tracker/templates/tracker/task_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
	<form method="post">
		{% csrf_token %}
		<p>Are you sure you want to delete "{{ object }}"?</p>
		{{ form }}
		<input type="submit" value="Confirm">
	</form>
{% endblock %}

tracker/templates/tracker/task_form.html
{% extends 'base.html' %}

{% block content %}
	<form method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Save">
	</form>
{% endblock %}

tracker/templates/tracker/task_update_form.html
{% extends 'base.html' %}

{% block content %}
	<form method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Update">
	</form>
{% endblock %}